language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jigneshkvp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jigneshkvp/docker-react npm run test